
IMAGE_NAME="openshift/origin-keepalived-ipfailover"


all:	image

test:	image
	(cd tests && ./verify_failover_image.sh)

image:
	docker build -t $(IMAGE_NAME) .

clean:
	docker run -it --net=host --privileged=true --entrypoint "/var/lib/ipfailover/keepalived/remove-failover.sh" $(IMAGE_NAME)
